name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Cypress Docker image
        uses: docker://cypress/included:13.10.0
        with:
          args: >
            bash -c "npm ci && npx cypress run"

      - name: Archive Mochawesome Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: mochawesome-report
          path: results/mochawesome_results/