name: Cypress Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests inside Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/e2e \
            -w /e2e \
            cypress/included:13.10.0 \
            npx cypress run --spec "cypress/e2e/2-advanced-examples/actions.cy.js"

      - name: Fix permissions on results directory
        run: sudo chown -R $USER:$USER ./results

      - name: Merge Mochawesome Reports
        run: npm run merge_reports

      - name: Generate Mochawesome HTML Report
        run: npm run mochawesome_report

      - name: Archive Mochawesome HTML Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: mochawesome-html-report
          path: results/mochawesome-html-report/