name: Cypress Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests with Mochawesome reporting
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/e2e \
            -w /e2e \
            cypress/included:13.10.0 \
            /bin/bash -c "npm run cleanup && npm run cy_dashboard && npm run merge_reports && npm run mochawesome_report"
        env:
          # Adding DISPLAY variable to handle potential X connection issues
          DISPLAY: ":99.0"
          CI: true

      - name: Archive Mochawesome HTML Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: mochawesome-html-report
          path: results/mochawesome-html-report/